### ISSUE TITLE
Identifier with trailing underscore

### ISSUE THREAD

**Issue by opk12** [twolfson/restructuredtext-lint#55] opened 2020-04-02 18:49 UTC
A variable name with a trailing underscore gives `Unknown target name`. This seems the same as [sphinx issue 1462](https://github.com/sphinx-doc/sphinx/issues/1462), in fact the namedtuple reproducer is taken from there.

```
$ cat test.py
def f(id_: str):
    """Function.

    :param id_: A string."""
    print()



X = collections.namedtuple(
    'X',
    ('subject', 'from_', 'to', 'body',)
)
```

```
$  restructuredtext-lint test.py
WARNING test.py:5 Field list ends without a blank line; unexpected unindent.
WARNING test.py:12 Definition list ends without a blank line; unexpected unindent.
ERROR test.py:7 Unknown target name: "id".
ERROR test.py:4 Unknown target name: "id".
ERROR test.py:10 Unknown target name: "from".
```

In turn, this gives error in flake8 via [flake8-rst-docstrings/](https://pypi.org/project/flake8-rst-docstrings/).

**Comment by twolfson** [comment] 2020-04-02 18:59
I'm confused by this usage of `rst-lint`, We've only designed it to parse `.rst` files, not extract docstrings and lint those

From my perspective, it actually seems like `rst-lint` is working as intended since a `_` suffix indicates a link target so it should expect a matching target

As a result, this seems like this issue is exclusive to Sphinx since that's designed to handle `:param:` fields whereas `rst-lint` has no designation/special handling for those

Closing as `invalid` for now

**Closed by twolfson** 2020-04-02 18:59 UTC
