### ISSUE TITLE
Anonymous links not handled correctly 

### ISSUE THREAD

**Issue by harlowja** [twolfson/restructuredtext-lint#12] opened 2015-03-04 18:36 UTC
It appears that the following happens when anonymous references are used.

http://logs.openstack.org/13/161113/6/check/gate-openstack-manuals-tox-checkniceness/e2e5ba6/console.html

The rst that caused this @ https://review.openstack.org/#/c/161113/6/doc/hot-guide/source/existing_templates.rst

It appears links/references that are anonymous don't have line numbers so can't be accessed in this manner (and therefore blow up the linting error handler).

**Comment by twolfson** [comment] 2015-03-04 18:41
I will take a look by the end of this weekend. Thanks!

**Comment by dsneddon** [comment] 2015-03-04 18:51
To add a little bit more info, in this case I had used double trailing underscores yet still tried to treat it as a named link. Example:
=====
The `OpenStack TripleO Heat Templates repository`__ contains a variety of heat templates that are included in the tripleo-heat-templates codebase.

.. _OpenStack TripleO Heat Templates: http://git.openstack.org/cgit/openstack/tripleo-heat-templates/tree/
=====
I'm not sure if the check would have been confused if I had used a properly formatted anonymous link, but at least the reported problem is reproducible with the above.

**Comment by twolfson** [comment] 2015-03-04 19:05
Yea, I saw that. In any case though, the linter should either be reporting or ignoring it, not throwing errors.

**Comment by twolfson** [comment] 2015-03-05 07:30
Alright, took a look. It was an easy fix: the error had no line associated with it since it was more about the file. To fix it, we moved from `['line']` to `.get('line')`.

The error itself should read something like "Anonymous hyperlink mismatch: 1 references but 0 targets."

This has been patched and released in `0.11.0`.

**Closed by twolfson** 2015-03-05 07:30 UTC
